---
title: "Overview of R for assignments"
author: "Jinko Graham"
date: '2018-08-14'
output: pdf_document
---


[R](http://www.r-project.org) is a powerful environment for
statistical computing and graphics. We will be using R for
homework assignments as it is supported by the Stats Workshop. 
I would not say that you will "learn R" in this course. 
Instead you'll get example code in class notes or templates that you can 
modify to do your analyses. Your focus should be on getting
practice with data wrangling, analysis, and **interpretation**
of the results. In the course of doing the homework assignments
you will probably pick up a bit of R and you will have a set of
templates for doing future analyses (e.g., as a lab assistant 
at SFU), but you will not be a serious R user. Students
interested in learning R should consider taking Stat 341.

R may be downloaded from the 
[Comprehensive R Archive Network](http://cran.r-project.org) 
and comes with its own user interface called the R console.
However, I recommend that you use one of the following three 
R user interfaces, because they all have facilities for
integrating text, R code and R output that will simplify 
the process of doing your assignments:

1. RStudio Desktop -- To get started, see [Getting started with R and RStudio](https://github.com/SFUStatgen/RforStat2/blob/master/Tutorials/GettingStarted/startR-RStudio.Rmd) for instructions.
2. RStudio Cloud -- To get started, see [Getting started with RStudio Cloud](https://github.com/SFUStatgen/RforStat2/blob/master/Tutorials/GettingStarted/startRStudioCloud.Rmd) for instructions.
3. R via Jupyter -- To get started, see the Stat Workshop's R/Jupyter page  [**ADD LINK to the Stat Workshop's R/Jupyter page for Fall 2018 once it is created**]

These interfaces are all supported by the Stat Workshop. A partial list of the pros and cons of each interface are given in the table below:

| Interface      | pros/cons | Comments                                           |
| -------------- | --------- | -------------------------------------------------- |
RStudio Desktop | pros | You install your own (free) copy on your personal computer. Has well-developed tools for authoring documents such as homework assignments. Supported by an extensive online community of users. Used in class demos. |
|   | cons  | Can be difficult to install for some with non-standard setups on their computers such as Chinese characters. |
| RStudio Cloud | pros | No installation required; instead access is through the internet. A CloudFront (Amazon) server with the same interface as RStudio Desktop. |
|    | cons  | As an internet server it can be slow to respond and experience outages. |
| R via Jupyter | pros | No installation required; instead access is through the internet. A UBC server with the Jupyter interface. Jupyter tutorials are available from the SFU Stat Workshop Canvas site.|
|   | cons | As an internet server for BC universities, it may have slowdowns or outages before assignments are due or during other high-volume periods of the semester. |


