---
title: "Instructions for Exercises"
author: "Brad McNeney"
date: "2019-01-10"
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Templates for exercise sets are
to be downloaded from the class website and 
modified to include your answers. 

**For each set of exercises** do the following:

* Download the template to your computer.
To do so, click on the link to the RMarkdown
(`.Rmd`) file if
you use RStudio (Desktop or Cloud) or the 
Jupyter notebook (`.ipynb`) if you use Jupyter.
Look for and click the "Raw" button near the top of the web page to see the 
file in its raw form. Use your browser's 
`File -> Save As`
feature to save the file to the appropriate folder on your computer (e.g. the folder where you do you Stat305 exercises).
    + Note 1: Some computers will add or ask to add a ".txt" extension to the file. Say "no" or, if it has been added, remove the ".txt" extension manually yourself. Otherwise, RStudio won't recognize the .Rmd file and Jupyter won't recognize the .ipynb file.
    + Note 2: The default to save .Rmd files in Safari
    is as a "Web Archive". Do **not** use this default.
    Instead, save as "Page Source".
* If your R interface is a server (RStudio Cloud or
Jupyter), upload the template to the server.
For example, RStudio Cloud users can use the upload button 
found in the files pane in the lower right corner of their RStudio.
    + Jupyter users will find that the templates require a
    few minor modifications before you start. See
    the instructions [here](https://github.com/SFUStatgen/RforStat2/blob/master/SFUStat305/Exercises/Instructions/TemplateMods.pdf)
* Start your R interface and open the template.
* Change the name, student ID and date in the 
header of the template to your own.
* Add your answers to the template.
* When you are finished adding your
answers, knit (RStudio) or run (Jupyter) the 
document to an HTML file. Save this 
file for reference during the quiz based on the 
exercise set.