---
title: "Getting started with RStudio Cloud"
author: "Jinko Graham"
date: '2018-08-03'
output: pdf_document
---

RStudio Cloud is a cloud-based interface to R. The interface looks like the usual desktop version of RStudio. To get started, follow the steps below.

1. Go to [https://rstudio.cloud/], click the "Get Started" button and follow the prompts to sign up for the service.
2. When you first log in to RStudio Cloud you will have a personal workspace called "Your Workspace" with no content. It is recommended that you click the "New Project" button to create a container for all your Stat 305 work.
3. When the new project loads you will see the RStudio interface. Click the text "Untitled Project" beside "Your Workspace" at the top of the browser window and enter an informative name for your project, such as Stat 305.
4. The RStudio interface is divided into three panes, with multiple tabs in each pane. You can type R commands into the R console tab of the left-hand pane.
5. Now is a good time to install some R packages. Go the the bottom-right pane and switch from the "Files" tab to the "Packages" tab. Click "Install", enter "tidyverse" (without the quotes) in the "Packages" field of the pop-up window and click the "Install" button. You will have to wait several minutes while a series of packages is installed.
6. When you want to log out, click your name in the top-right of the browser window and choose "log out".

The next time you want to use RStudio Cloud, go to [https://rstudio.cloud/] and look for the "log in" link in the top-right of the browser window. Click the name of your project (e.g., Stat 305) to resume work. You should find that everything from your previous session, including the packages you installed, is available for use.
