---
title: "Assignment 1"
author: "Jinko Graham"
date: '2018-08-18'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This assignment consists of 5 questions. Templates
for each question are given in the numbered
list below:

1. Question 1 [RMarkdown](https://github.com/SFUStatgen/RforStat2/blob/master/SFUStat305/Assignments/A1/A1Q1.Rmd) or [Jupyter notebook](LINK TO BE ADDED)
2. Question 2 [RMarkdown](https://github.com/SFUStatgen/RforStat2/blob/master/SFUStat305/Assignments/A1/A1Q2.Rmd) or [Jupyter notebook](LINK TO BE ADDED)
3. Question 3 [RMarkdown](https://github.com/SFUStatgen/RforStat2/blob/master/SFUStat305/Assignments/A1/A1Q3.Rmd) or [Jupyter notebook](LINK TO BE ADDED)
4. Question 4 [RMarkdown](https://github.com/SFUStatgen/RforStat2/blob/master/SFUStat305/Assignments/A1/A1Q4.Rmd) or [Jupyter notebook](LINK TO BE ADDED)
5. Question 5 [RMarkdown](https://github.com/SFUStatgen/RforStat2/blob/master/SFUStat305/Assignments/A1/A1Q5.Rmd) or [Jupyter notebook](LINK TO BE ADDED)

**For each question** do the following:

* Download the question template to your computer.
To do so, click on the link to the RMarkdown
(`.Rmd`) file if
you use RStudio (Desktop or Cloud) or the 
Jupyter notebook (`.ipynb`) if you use Jupyter.
Look for and click the "Raw" button near the top of the web page to see the 
file in its raw form. Use your browser's 
`File -> Save As`
feature to save the file to the appropriate folder on your computer (e.g. the folder where you do you Stat305 homework assignments).
* If your R interface is a server (RStudio Cloud or
Jupyter), upload the template to the server.
For example, RStudio Cloud users can use the upload button 
found in the files pane in the lower right corner of their RStudio.
* Start your R interface and open the template.
* Change the name, student ID and date in the 
header of the template to your own.
* Add your answers to the template.
* When you are finished adding your
answers, knit (RStudio) or run (Jupyter) the 
document and save the output as a PDF file. 
    + RStudio Desktop users should knit their RMarkdown
    file to HTML, and then use their browser to print
    the HTML file to PDF.
    + RStudio Cloud users should 
    make the following change to the header of the template 
    (lines 1-6): replace the line
    `output: html_document` with `output: pdf_document`. Then
    knitting will produce a PDF file.
    + Jupyter users should follow the Stat Workshop 
    tutorials on printing assignments.
* Now follow the Stat Workshop's instructions for
uploading a question to Crowdmark.

