---
title: "Assignment 3, Question 3"
author: "Your Name Here; Your Student ID number Here"
date: 'Put date here in YYYY-MM-DD format'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Chapter 20, #5 (modified). 
In a study investigating maternal risk factors for congenital
syphilis, syphilis is treated as a dichotomous response variable,
where 1 represents the presence of disease in a 
newborn and 0 its absence.
(Note: Syphilis can be spread from an infected mother to the fetus during pregnancy or to the infant at birth. When born, the infant has congenital syphilis.)
The estimated coefficients from a logistic-regression model 
containing the explanatory variables of cocaine or crack use,
marital status, number of prenatal visits to a doctor,
alcohol use, and level of education are listed below.
The estimated intercept $\hat{\alpha}$ is not given.

| Variable                  | Coefficient  |
| ------------------------- | -----------: |
| Cocaine/Crack Use         | $1.354$      |
| Marital Status            | $0.779$      |
| Number of Prenatal Visits | $-0.098$     |
| Alcohol Use               | $0.723$      |
| Level of Education        | $0.298$      |

Report numerical answers to 3-4 significant digits.


(a)	As an expectant mother's number of prenatal
visits to the doctor increases, what happens to 
the probability that her child will be born with
congenital syphilis?

**Answer:**
*Insert your written comments here.*

(b) Marital status is a dichotomous random variable,
where the value 1 indicates that a woman is unmarried
and 0 that she is married. What are the relative odds
that a newborn will suffer from syphilis for unmarried *versus*
married mothers? 

**Answer:**
*Insert your written comments here.*

(c) Cocaine or crack use is also a dichotomous random variable;
the value 1 indicates that a woman used drugs during her
pregnancy and 0 that she did not. 
What is the estimated odds ratio that a child will be born
with congenital syphilis for women who used cocaine or
crack *versus* women who did not?

**Answer:**
*Insert your written comments here.*


(d) The estimated slope coefficient for cocaine or crack use
has standard error 0.162. Construct a 95\% confidence
interval for the population **odds ratio** using the 
pivotal method described in the class notes. 
You will need the critical value 1.96. 

**Answer:**
*Insert your written comments here.*
