---
title: 'Statistics 305/605: Introduction to Biostatistical Methods for Health Sciences'
subtitle: 'Getting Started with RStudio'
author: "Jinko Graham, Brad McNeney"
output: 
  beamer_presentation:
    includes:
      in_header: header_pagenum.tex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## The Stat Workshop

+ Workshop [hours and location](https://canvas.sfu.ca/courses/43539). 
+ BM office hours are Wed 11:00-noon in the Workshop.

## Getting Started with RStudio

+ In Stat305/605, 
    + software demos will be in **RStudio**  
        + RStudio allows you to better organize your work in R.
    + exercise templates will be in **R Markdown** 
        + R Markdown documents allow you to integrate your written comments with R commands and their output. 

## What is RStudio? 

+ RStudio is a free "integrated development environment" (IDE) for R. 
+ Basically it is an interface that makes it easier to work with R and get organized on your computer.

## What is R Markdown? 

+ R Markdown is a file format for making documents with R. 

+ An R Markdown document is written in markdown, a simple plain text format, and allows you to integrate chunks of embedded R commands as well as their output. 

+ R Markdown allows you to author documents in file formats such as PDF,  Word and HTML.  

+ The R-Markdown document interface is available in RStudio. (For Jupyter users, an R Markdown document is like a Jupyter Notebook.)

## Getting-Started Videos

+ Below are links to short videos to give a flavour of RStudio and R Markdown: 
\small

+ Katie Ann Jager on "Getting Started with RStudio" (time 8:53)
https://www.youtube.com/watch?v=ikGdOt1WJyo
+ Roger Marin on "Installing R and R Studio" (time 4:53) 
https://www.youtube.com/watch?v=cX532N_XLIs 
and "What is R Studio" (time 5:20) https://www.youtube.com/watch?v=riONFzJdXcs
+ Roger Peng on "R Markdown with RStudio"  (time 6:38) https://www.youtube.com/watch?v=DNS7i2m4sB0
+ Nicolas Horton on "First steps with R Markdown" (time 3:49) https://www.youtube.com/watch?v=w4hLT7WyjnM
+ Watch these on your own.

## R Resources on the Course Canvas Page

+ This [overview](https://github.com/SFUStatgen/RforStat2/blob/master/RTutorials/overview.Rmd) on R/RStudio options for the course. 

+ Note that the overview links to material on [getting started](https://github.com/SFUStatgen/RforStat2/blob/master/RTutorials/GettingStarted/startR-RStudio.Rmd) in R/RStudio.

## Example R Markdown File

+ After installing R, RStudio and the tidyverse, install the 
`gapminder` package.
+ Exercise: Make sure you can "knit" the [`example.Rmd`](https://github.com/SFUStatgen/RforStat2/blob/master/RTutorials/GettingStarted/example.Rmd) RMarkdown document in the getting started folder
of R tutorials.
    + To save this file to your computer, click the "Raw" button to
    switch to raw view, then use your browser's `File -> Save as` feature
    to save the file. If your browser tries to add a `.txt` extension, 
    you must **remove this extension**.
    + Once you have saved the file, open it in RStudio and click "Knit"
