---
title: "Getting started with R and RStudio"
author: "Brad McNeney"
date: '2018-08-03'
output: pdf_document
---


These notes are adapted from Brad McNeney's Stat 341 course. Information on getting started with R and RStudio is given below. Please **install R first**, and RStudio second.

## R

[R](http://www.r-project.org) is an open-source software environment for statistical computing and graphics. You can download R from the [Comprehensive R Archive Network (CRAN)](http://cran.r-project.org), a network of mirror sites that host the "base" R code and add-on packages for R. Please use the SFU mirror of CRAN to download the version of R for your system. Windows and Mac users can download and install pre-compiled binary versions. Mac users should download and install XQuartz before installing R. Linux users may find pre-compiled versions for their distribution, but if not will have to install from the source code.

## RStudio

[RStudio](http://www.rstudio.com_) is an integrated development environment for R, developed by a company of the same name. You will need to have R installed on your system before installing RStudio. [Download](https://www.rstudio.com/products/rstudio/download/) the version of RStudio for your computer. For Windows and Mac the software is installed by a user-friendly installer. I have never installed for Linux.

## RStudio Projects

Your work in Stat 305 should be contained in an RStudio "Project". You can read more about RStudio Projects [here](https://support.rstudio.com/hc/en-us/articles/200526207-Using-Projects). We've also prepared a short [step-by-step tutorial](https://github.com/SFUStatgen/RforStat2/blob/master/RTutorials/CreateProjRStudio/createProj.pdf)
on creating a project.

## R packages

R packages can be installed from the
```
Tools -> Install Packages ...
```
menu item or by clicking "Install" from  the "Packages" tab on the bottom-right pane of the RStudio. Enter a comma-separated list of package names on the pop-up menu. Make sure the "Install Dependencies" check box is checked and then click "Install".

As part of getting started, **please be sure to install
`tidyverse`**. Tidyverse is a collection of packages for 
common data science tasks such as reading, manipulating
and graphical display of data. It includes the 
`dplyr` and `ggplot2` packages that we will use frequently.


## Known issues with installation

1. Character set mixup.
Some Macs display errors like the following when you start R:
```
During startup - Warning messages:
1: Setting LC_CTYPE failed, using "C" 
2: Setting LC_COLLATE failed, using "C" 
3: Setting LC_TIME failed, using "C" 
4: Setting LC_MESSAGES failed, using "C" 
5: Setting LC_PAPER failed, using "C"
```
If this happened to you, it is apparently because R is confused about what character set to use. You need to manually set the character set for R on your system. Outside of R, open a Mac terminal, type the following:
```
defaults write org.R-project.R force.LANG en_US.UTF-8
```
and then close the terminal. Now restart RStudio.

2. Install from source?
You may be asked something like the following during installation of a package:
```
There is a binary version available but the source version is later: 
Do you want to install from sources the package which needs compilation? y/n: 
```
Answer No. You likely don't have the necessary tools on your computer to build a package from its source code. You need the pre-compiled binary versions of packages.

3. Missing fonts.
You may see an error about "missing polygons" or other shapes when trying to do graphics due to missing or disabled fonts on your system. See a recent [stackexchange](http://stackoverflow.com/questions/10581440/error-in-grid-calll-textbounds-as-graphicsannotxlabel-xx-xy-polygon) conversation for some tips on how to resolve the issue.
